module.exports = {
  TOKEN_ERROR: "INVALID or EXPIRED token ",
  NO_TOKEN: "Token required to access API.",
  INVALID_BODY: "Request body is invalid.",
  EMAIL_ALREADY_EXISTS: "Email already exits",
  DATA_SAVED: "Request completed and data saved.",
  DATA_NOT_SAVED: "Request completed and data not saved.",
  DATA_RETRIEVED: "Request completed and data retrieved.",
  DATA_DELETED: "Request completed and data deleted.",
  DATA_UPDATED: "Request completed and data updated.",
  RECORD_NOTFOUND: "Record not found",
  DATA_NOT_FOUND: "No data found against this query",
  PASSOWRD_MISMATCH: "Old password didn't match",
  PASSOWRD_ERROR: "Password didn't match",
  PASSWORD_UPDATED: "Password has been updated",
  USER_NOTFOUND: "User doesn't exist",
  USER_SIGNEDIN: "User is signed-in",
  USER_LOGGEDOUT: "User is logged-out",
  RECORD_NOTFOUND: "Record not found",
};
